<a href="https://colab.research.google.com/github/rahmanidashti/TF2Practices/blob/main/00_TF2Practice_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installation and Import

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## Tensors

### Constant
A constant is a tensor that we cannot change its value when we create it. We defined a scaler, vector, and matrix using constant bellow.

In [ ]:
c1 = tf.constant(2, tf.int16)
c2 = tf.constant([4, 1, 2], tf.int16)
c3 = tf.constant([[1,2,3],[4,5,6]], tf.int16)

print(c1)
print(c2)
print(c3)

tf.Tensor(2, shape=(), dtype=int16)
tf.Tensor([4 1 2], shape=(3,), dtype=int16)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int16)


### Variable
The difference between variable and constant is that we can change its value whenever we need but we cannot change its type as we could not in constant.

In [ ]:
v1 = tf.Variable(2, tf.int16)

print(v1)

v1.assign(4)

print(v1)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>


### Sparse Tensor

Sparse Tensor is a suitable way when you want to store a sparse data such as a user-item interaction matrix which most of the elements are zero.

In [ ]:
s1 = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[4, 7], dense_shape=[2, 3])

print(s1)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([4 7], shape=(2,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))


## Static Computation Graph in TF.2

In `TF.2` to create a static computation graph we need to use `TF.Function`. For more information you can read the following blog post on **Meduim** which is very usefule and contains different examples: [Practical Coding in TensorFlow 2.0 (Eager execution, @tf.function, TensorArray, and advanced control flow)](https://towardsdatascience.com/practical-coding-in-tensorflow-2-0-1aab32bcfde1)

In [ ]:
@tf.function
def multiply_test(p1, p2):
  m = tf.multiply(p1, p2)
  return m

c1 = tf.constant(2, tf.int16)
c2 = tf.constant(4, tf.int16)

result = multiply_test(c1, c2)
tf.print(result)

8
